name: 'Get a changelog between two references'
author: 'Chad Metcalf'
description: 'Returns the commit difference count between two git references.'
inputs:
  mytoken:
    description: 'Your GITHUB_TOKEN'
    default: ''
    required: true
  head-ref:
    description: 'The name of the head reference'
    default: ''
    required: false
  base-ref:
    description: 'The name of the base reference'
    default: ''
    required: false
  reverse:
    description: 'Git log is chronological order by default. Set to true to reverse chronological order. '
    default: 'false'
    required: false
  fetch:
    description: 'Whether to have this action fetch all other branches and tags'
    default: 'true'
    required: false
outputs:
  changelog:
    description: 'Markdown formatted changelog'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'list'
  color: 'blue'
