name: 'Get a changelog between two references'
author: 'Chad Metcalf'
description: 'Returns the commit difference count between two git references.'
inputs:
  mytoken:
    description: 'Your GITHUB_TOKEN'
    default: ''
    required: true
  head-ref:
    description: 'The name of the head reference'
    default: ''
    required: false
  base-ref:
    description: 'The name of the base reference'
    default: ''
    required: false
  firstRelease:
    description: >
      The flag of base-ref setting when no release. Default `"commit"`.

      If your repository has never published a release,
      you can set the base reference through this parameter.

      When this parameter is set to "commit", the base reference will be set to initial commit.
      When this parameter is set to "tag", the base reference will be set to the latest tag.
    default: 'commit'
    required: false
outputs:
  changelog:
    description: 'Markdown formatted changelog'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'list'
  color: 'blue'
