name: test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@main
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
          head-ref: 'v0.0.2'
          base-ref: 'v0.0.1'
      - name: Reverse the generated changelog
        id: changelog-rev
        uses: metcalfc/changelog-generator@main
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
          head-ref: 'v0.0.2'
          base-ref: 'v0.0.1'
          reverse: 'true'
      - name: Explicitly do not reverse the generated changelog
        id: changelog-notrev
        uses: metcalfc/changelog-generator@main
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
          head-ref: 'v0.0.2'
          base-ref: 'v0.0.1'
          reverse: 'false'
      - name: Get the changelog
        run: |
          cat << "EOF"
          ${{ steps.changelog.outputs.changelog }}
          EOF
      - name: Modify the changelog
        id: modified
        run: |
          set -o noglob
          log=$(cat << "EOF" | grep -v Bumping | tac
          ${{ steps.changelog.outputs.changelog }}
          EOF
          )
          log="${log//'%'/'%25'}"
          log="${log//$'\n'/'%0A'}"
          log="${log//$'\r'/'%0D'}"
          echo "modified=$log" >> $GITHUB_OUTPUT
      - name: Print the modified changelog
        run: |
          cat << "EOF"
          ${{ steps.modified.outputs.modified }}
          EOF
      - name: Generate changelog from release
        id: release
        uses: metcalfc/changelog-generator@main
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Get the changelog
        run: |
          cat << "EOF"
          ${{ steps.release.outputs.changelog }}
          EOF
