name: commit
on: [push]

jobs:
  commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const result = await github.repos.listCommits({ context.repo.owner, context.repo.repo, });
            console.log(result);
